# Generated by Django 5.1.3 on 2025-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_stripe", "0002_shippinginfo_checkoutsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
